### PR TITLE
[feature/file-structure] basic file structure and node modules

### PR DESCRIPTION
**Pull request by pepemiyashiro**

### CODE REVIEW

**Review by luissardon — CHANGES_REQUESTED** [review]
use minor modules version

**Comment by pepemiyashiro** [comment]
@luissardon done

**Review by luissardon — APPROVED** [review]

**Comment by pepemiyashiro** [comment]
A ver

**Comment by pepemiyashiro** [comment]
ver 2

**Comment by pepemiyashiro** [comment]
suena?

**Comment by pepemiyashiro** [comment]
pray it  does not sound

**Comment by pepemiyashiro** [comment]
hell yeah

**Pull request merged**
